version: '3.3'
services:
  jenkins:
    image: "jenkinsdocker:latest"
    networks:
      - jd_net
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkinsdocker:/var/jenkins_home"
      - "./groovy:/var/jenkins_home/init.groovy.d"
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkinsdocker:
networks:
  jd_net:
