version: '3.3'
services:
  jenkins:
    image: "jenkinsdocker:2.235.2"
    networks:
      - jd_net
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jd_volume:/var/jenkins_home"
      - "./groovy:/var/jenkins_home/init.groovy.d"
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jd_volume:
networks:
  jd_net:
