version: '3.5'
services:
  jenkins:
    image: "jenkinsdocker:2.235.3"
    container_name: jenkins
    networks:
      - cicd_net
    ports:
      - "8080:8080"
      - "8443:8443"
      - "50000:50000"
    volumes:
      - "$HOME/Data/jenkins/jenkins_home:/var/jenkins_home"
      - "./groovy:/var/jenkins_home/init.groovy.d"
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  sonarqube:
    image: "sonarqube:8.4.1-community"
    container_name: sonar
    networks:
      - cicd_net
    ports:
      - "9000:9000"
      - "9092:9092"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    volumes:
      - "sonarqube_volume:/opt/sonarqube"
    restart: always

  nexus:
    image: "sonatype/nexus3:3.25.1"
    container_name: nexus
    networks:
      - cicd_net
    ports:
      - "8081:8081"
      - "8082:8082"
      - "5000:5000"
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx2g -XX:MaxDirectMemorySize=3g
      - NEXUS_CONTEXT=nexus
      - CONTEXT_PATH=/
    volumes:
      - "nexus-data:/nexus-data"
    restart: always

  clair-postgres:
    image: "arminc/clair-db:latest"
    container_name: clair-postgres
    networks:
      - cicd_net
    ports:
      - "5432:5432"
    volumes:
      - clair-postgres:/var/lib/postgresql/data
    restart: always

  clair:
    image: "quay.io/coreos/clair:latest"
    container_name: clair
    command: [-config, /config/config.yaml]
    networks:
      - cicd_net
    ports:
      - "6060:6060"
      - "6061:6061"
    volumes:
      - ./clair-config.yaml:/config/config.yaml
    restart: always

volumes:
  sonarqube_volume:
  nexus-data:
  clair-postgres:

networks:
  cicd_net:
    name: cicd_net
    driver: bridge
